name: Build CSGO SteamFix

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v4

      - name: Install Compilers
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y g++-multilib build-essential

      - name: Manual Compile
        run: |
          # Компілюємо один єдиний файл main.cpp
          # Використовуємо внутрішню папку sdk, яка вже є в репо
          g++ -O3 -m32 -shared -fPIC \
            -o csgo_steamfix.ext.so \
            main.cpp \
            -D_LINUX -DPOSIX -D_alloca=alloca -DSOURCEMOD_BUILD -DEXT_WORKING \
            -I. \
            -I./sdk

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: csgo-steamfix-linux
          path: csgo_steamfix.ext.so
