name: Build Extension (AMBuild)

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v4
        with:
          path: plugin
          submodules: recursive

      - name: Checkout Dependencies (SDKs)
        run: |
          git clone --depth 1 https://github.com/alliedmodders/sourcemod --branch master sourcemod
          git clone --depth 1 https://github.com/alliedmodders/metamod-source --branch master metamod
          git clone --depth 1 https://github.com/alliedmodders/hl2sdk --branch csgo hl2sdk-csgo
          git clone --depth 1 https://github.com/alliedmodders/ambuild ambuild

      - name: Install Python & AMBuild
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y g++-multilib python3-pip
          pip3 install ./ambuild

      - name: Build Extension
        working-directory: plugin
        run: |
          python3 configure.py --sm-path="${{ github.workspace }}/sourcemod" --mm-path="${{ github.workspace }}/metamod" --hl2sdk-root="${{ github.workspace }}"
          ambuild

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: csgo-steamfix-linux
          path: plugin/build/package/addons/sourcemod/extensions/*.so
